# Generated by Django 3.2.16 on 2023-01-21 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakazlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=50)),
                ('shahar', models.CharField(max_length=50)),
                ('tur', models.CharField(max_length=20)),
                ('miqdor', models.CharField(max_length=20)),
                ('vaqt', models.DateTimeField(default=datetime.datetime(2023, 1, 22, 2, 5, 27, 183318))),
            ],
        ),
    ]
