# Generated by Django 3.2.16 on 2023-01-22 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itnomi', models.CharField(max_length=100)),
                ('coment', models.TextField()),
                ('img', models.ImageField(default='', upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'it',
                'verbose_name_plural': 'Itlar',
            },
        ),
        migrations.AlterField(
            model_name='zakazlar',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 21, 54, 4, 727452)),
        ),
    ]
