# Generated by Django 3.2.16 on 2023-01-22 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230122_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakazlar',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 22, 24, 20, 811810)),
        ),
    ]
