# Generated by Django 3.2.16 on 2023-01-22 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_zakazlar_vaqt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itnomi', models.CharField(max_length=100)),
                ('coment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='zakazlar',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 22, 27, 23, 693103)),
        ),
    ]
