# Generated by Django 3.2.16 on 2023-01-22 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230122_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axborot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'Infos',
            },
        ),
        migrations.AlterField(
            model_name='zakazlar',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 23, 39, 53, 693896)),
        ),
    ]
